### ISSUE TITLE
Create a preview on firebase and add a github action to post to it

### ISSUE THREAD

**Issue by ShaneBonkowski** [ShaneBonkowski/ShanesGames#168]
This code in the workflows/deploy-website.yml posts the website on merge to main:
```
- name: Deploy to Firebase Hosting
   uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLACK_HOLE_REJECT }}
          channelId: live
          projectId: black-hole-reject
```

It would be nice to make a `demo` or 'preview' branch or similar that instead of posting to the live actual website, posts to a preview website for development and/or testing that only I can see. This would trigger on merge to 'demo' or 'preview' branch. Check and see how simple this is to implement. Note that firebase setup created something like this originally that I deleted:

```
# This file was auto-generated by the Firebase CLI
# https://github.com/firebase/firebase-tools

# Name of the GitHub Actions workflow
name: Deploy to Firebase Hosting on PR

# Trigger the workflow on pull request events
on: pull_request

# Define permissions required for the workflow to run
permissions:
  checks: write          # Write access to checks
  contents: read         # Read access to contents
  pull-requests: write  # Write access to pull requests

# Define the jobs to be executed
jobs:
  # Define a job named 'build_and_preview'
  build_and_preview:
    # Specify that this job should only run if the pull request originates from the same repository
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    # Specify the operating system for the job
    runs-on: ubuntu-latest
    # Define the steps to be executed in this job
    steps:
      # Step 1: Checkout the repository code
      - uses: actions/checkout@v4
      # Step 2: Install project dependencies and build the project
      - run: npm ci && npm run build
      # Step 3: Deploy the project to Firebase Hosting using a custom GitHub Actions action
      - uses: FirebaseExtended/action-hosting-deploy@v0
        # Specify input parameters for the action
        with:
          # GitHub token used for authentication and authorization
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          # Service account key used for authenticating with Firebase services
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLACK_HOLE_REJECT }}
          # ID of the Firebase project where the project will be deployed
          projectId: black-hole-reject

```

Maybe this is similar is a good way to get a preview posted?
